### ISSUE TITLE
\textit{a} instances are not converted properly can it be added as emphasis ?

### ISSUE THREAD

**Issue by sonali8434** [LiNk-NY/Rnw2Rmd#4]
Hello @mtmorgan and @LiNk-NY,

I am an Outreachy Intern at Bioconductor, working on the Swaeve2rmd project mentored by @jwokaty. 

Thank you for working on Lua. This Lua code handles most of the problems we face while using pandoc. 

During the conversion using this template - https://github.com/lwaldron/sweave2rmd_conversiontemplate by @lwaldron, I noticed that the current code does not handle `\textit{a}` instances during conversion. I think we can add it as emphasis in your code.

I am interested in working on it. I will test this code in a few more conversions and let you know if I can help you in any way.

Thank you for your time.

**Comment by mtmorgan** [comment]
I think it might be as easy as adding a line at https://github.com/LiNk-NY/Rnw2Rmd/blob/091bd57e85df60c84fe974ece7e23396b38bc85a/inst/lua/BiocStyle.lua#L34 that translates `textit` to `emphasis`. Good luck, and thanks in advance!

**Comment by LiNk-NY** [comment]
Thanks Martin! Testing with `Rnw2Rmd-test.Rnw`, `Rnw2RmdPandoc` yields italicized markdown for the `textit` tag.

**Comment by sonali8434** [comment]
> I think it might be as easy as adding a line at
> 
> https://github.com/LiNk-NY/Rnw2Rmd/blob/091bd57e85df60c84fe974ece7e23396b38bc85a/inst/lua/BiocStyle.lua#L34
> 
> that translates `textit` to `emphasis`. Good luck, and thanks in advance!

Thanks I will do that.

**Comment by sonali8434** [comment]
> Thanks Martin! Testing with `Rnw2Rmd-test.Rnw`, `Rnw2RmdPandoc` yields italicized markdown for the `textit` tag.

Its correct It should be italicized for \textit{ } instances.
