### ISSUE TITLE
Request of adding Readme file to give instructions to new users. 

### ISSUE THREAD

**Issue by sonali8434** [LiNk-NY/Rnw2Rmd#5]
Hello @LiNk-NY, I and @jwokaty have noticed that your package does not have a readme file containing information about how to use it. We are planning to include your package in our contribution document, and it would be really helpful if your package had a readme file. This way, new users can understand how to use it. If you agree, we can make a pull request to add a readme file to your package.

Thank you for your time.

**Comment by LiNk-NY** [comment]
Typically for small packages such as this one, the `README.md` is the rendered version of the vignette. I have not worked on the vignette but if you'd like send a pull request with a draft of the vignette, that would be great. Thanks!

**Comment by lwaldron** [comment]
Basic vignette draft introduced by PR https://github.com/Bioconductor/Rnw2Rmd/pull/6

**Comment by LiNk-NY** [comment]
I have added a README.md based on Levi's vignette. Thanks!
